# 1. Read and Show Image

In [1]:
import cv2

## Image Read and Show

In [4]:
img =cv2.imread(r'E:\Computer-Vision\Images\boat.jpg') # read image
cv2.imshow('Boat Image',img) # show image
cv2.waitKey(10000)  # image frame wait time-ms and 0 pass keyboard any key press
# cv2.destroyAllWindows()  # all window close
cv2.destroyWindow('Boat Image')  # only one window close give particular window name


## Image Multiple Window Open

In [5]:
img =cv2.imread(r'E:\Computer-Vision\Images\boat.jpg') # read image
cv2.imshow('Boat Image',img) # show image
cv2.imshow('Boat Image',img) # show image
cv2.waitKey(0)  # image frame wait time-ms and 0 pass keyboard any key press
cv2.destroyAllWindows()  # all window close
# cv2.destroyWindow()  # only one window close

## Resize Image

In [6]:
img =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg') # read image

#Resize image width ,height
img =cv2.resize(img,(500,500))

cv2.imshow('Cat Image',img) # show image
cv2.waitKey(0)  # image frame wait time-ms and 0 pass keyboard any key press
# cv2.destroyAllWindows()  # all window close
cv2.destroyWindow('Cat Image')  # only one window close give particular window name


In [9]:
import numpy as np
v =np.array([[1,2,3,1,2,3],[1,2,3,1,2,3]])
v

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [10]:
img =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg') # read image
print(img) #RGB

[[[  5  22  35]
  [  7  24  37]
  [ 10  27  40]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 [[  8  25  38]
  [  9  26  39]
  [  9  28  41]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 [[ 13  30  43]
  [ 12  31  44]
  [ 12  31  46]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 ...

 [[  9  14  17]
  [  4   9  12]
  [  9  14  17]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]

 [[ 22  27  30]
  [  5  10  13]
  [  9  14  17]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]

 [[ 40  45  48]
  [ 10  15  18]
  [ 10  15  18]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]]


# 2. Show Multiple Image and Slide Show
### Horizontal and Vertical

In [11]:
img =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg')

#Resize image width ,height
img =cv2.resize(img,(200,200))

#Show horizontal multiple image in one frame
h =np.hstack((img,img))

#Show vertical multiple image in one frame
v =np.vstack((h,h))

cv2.imshow('Lion Image',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Slide Image Show

In [13]:
import os
# show all images with help of os
list_name =os.listdir(r'E:\Computer-Vision\Images')
list_name

['boat.jpg',
 'cat.jpg',
 'chair.jpg',
 'clock.jpg',
 'dog.jpg',
 'elephant.jpg',
 'fan.jpg',
 'Honda Civic.jpg',
 'laptop.jpg',
 'lion.jpg']

In [15]:
for name in list_name:
    path ='E:\\Computer-Vision\\Images'
    img_name = path + '\\' + name 
    img = cv2.imread(img_name)
    img =cv2.resize(img,(200,200))
    cv2.imshow('Different Images',img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()
    