# 1. Read and Show Image

In [1]:
import cv2
import numpy as np

## Image Read and Show

In [4]:
img =cv2.imread(r'E:\Computer-Vision\Images\boat.jpg') # read image
cv2.imshow('Boat Image',img) # show image
cv2.waitKey(10000)  # image frame wait time-ms and 0 pass keyboard any key press
# cv2.destroyAllWindows()  # all window close
cv2.destroyWindow('Boat Image')  # only one window close give particular window name


## Image Multiple Window Open

In [5]:
img =cv2.imread(r'E:\Computer-Vision\Images\boat.jpg') # read image
cv2.imshow('Boat Image',img) # show image
cv2.imshow('Boat Image',img) # show image
cv2.waitKey(0)  # image frame wait time-ms and 0 pass keyboard any key press
cv2.destroyAllWindows()  # all window close
# cv2.destroyWindow()  # only one window close

## Resize Image

In [6]:
img =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg') # read image

#Resize image width ,height
img =cv2.resize(img,(500,500))

cv2.imshow('Cat Image',img) # show image
cv2.waitKey(0)  # image frame wait time-ms and 0 pass keyboard any key press
# cv2.destroyAllWindows()  # all window close
cv2.destroyWindow('Cat Image')  # only one window close give particular window name


In [9]:
import numpy as np
v =np.array([[1,2,3,1,2,3],[1,2,3,1,2,3]])
v

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [10]:
img =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg') # read image
print(img) #RGB

[[[  5  22  35]
  [  7  24  37]
  [ 10  27  40]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 [[  8  25  38]
  [  9  26  39]
  [  9  28  41]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 [[ 13  30  43]
  [ 12  31  44]
  [ 12  31  46]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 ...

 [[  9  14  17]
  [  4   9  12]
  [  9  14  17]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]

 [[ 22  27  30]
  [  5  10  13]
  [  9  14  17]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]

 [[ 40  45  48]
  [ 10  15  18]
  [ 10  15  18]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]]


# 2. Show Multiple Image and Slide Show
### Horizontal and Vertical

In [11]:
img =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg')

#Resize image width ,height
img =cv2.resize(img,(200,200))

#Show horizontal multiple image in one frame
h =np.hstack((img,img))

#Show vertical multiple image in one frame
v =np.vstack((h,h))

cv2.imshow('Lion Image',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Slide Image Show

In [13]:
import os
# show all images with help of os
list_name =os.listdir(r'E:\Computer-Vision\Images')
list_name

['boat.jpg',
 'cat.jpg',
 'chair.jpg',
 'clock.jpg',
 'dog.jpg',
 'elephant.jpg',
 'fan.jpg',
 'Honda Civic.jpg',
 'laptop.jpg',
 'lion.jpg']

In [15]:
for name in list_name:
    path ='E:\\Computer-Vision\\Images'
    img_name = path + '\\' + name 
    img = cv2.imread(img_name)
    img =cv2.resize(img,(200,200))
    cv2.imshow('Different Images',img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()
    

# 3. Image imread Function (RGB,grayscale)

In [2]:
# 1 is used for RGB color image flag is 1
import cv2
img = cv2.imread(r'E:\Computer-Vision\Images\clock.jpg', 1)
img = cv2.resize(img,(200,200))
cv2.imshow("RGB Image flag = 1",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# 0 is used for grayscale image flag is 0
import cv2
img = cv2.imread(r'E:\Computer-Vision\Images\clock.jpg', 0)
img = cv2.resize(img,(200,200))
cv2.imshow("Grayscale Image flag = 0",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 4. Text Over a Image

In [1]:
import cv2


In [71]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\clock.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(500,600))

# Draw text on image parameters
img =img_get
text ='Clock Image' # text to be added
org = (150, 50)  # position of text
fontFace = cv2.FONT_HERSHEY_DUPLEX # font type
fontscale = 1 # font scale
color = (0, 255, 0)  # BGR color format
thickness = 2  # thickness of text
lineType =cv2.LINE_8 # line type
bottomLeftOrigin = False  # text origin



txt =cv2.putText(img, text, org, fontFace, fontscale, color, thickness, lineType, bottomLeftOrigin)

cv2.imshow('Clock Image',img_get) 
cv2.waitKey(0)
cv2.destroyAllWindows()


# 5. Draw Line and Rectangle on Image 

In [61]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(400,400))

# Draw line on image change parameters
img =cv2.line(img_get, pt1=(200, 100),pt2= (300 , 100), color =(255, 0, 0), thickness=4,lineType =4)  # line start point, end point, color, thickness

cv2.imshow('Lion Image',img) 
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(400,400))

# Draw text on image parameters
img =img_get
text ='lion' # text to be added
org = (170, 25)  # position of text
fontFace = 2 # font type
fontscale = 1 # font scale
color = (0, 0, 255)  # BGR color format
thickness = 2  # thickness of text
lineType = 16 # line type
bottomLeftOrigin = False  # text origin

txt =cv2.putText(img, text, org, fontFace, fontscale, color, thickness, lineType, bottomLeftOrigin)

 
# Draw Rectangle on image change parameters
img =cv2.rectangle(img_get, pt1=(170, 30),pt2= (320 , 300), color =(0, 255, 0), thickness=2,lineType =16)  # line start point, end point, color, thickness

cv2.imshow('Lion Image',img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# 6. Draw Circle and Elllipse On Image

In [122]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\dog.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(400,400))

# Draw circle on image change parameters if thickness =-1 then circle is filled
img =cv2.circle(img =img_get, center=(300, 100), radius=65, color=(0, 0, 255), thickness=2, lineType=16)  # center point, radius, color, thickness



cv2.imshow('Dog Image',img_get) 
cv2.waitKey(0)
cv2.destroyAllWindows()


In [159]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\dog.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(400,400))


# write text on image
txt_img =cv2.putText(img_get, 'Dog', (250, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2, cv2.LINE_AA)



# Draw Ellipsis on image change parameters if thickness =-1 then circle is filled
img =cv2.ellipse(img =img_get, center=(305, 115), axes =(35,60), 
                 angle =10, startAngle =0, endAngle =360,
                 color=(0, 0, 255), thickness=2,
                 lineType=16)  # center point , color, thickness


cv2.imshow('Dog Image',img_get) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# 7. Arithmetic Operation on Image using Opencv

In [173]:
img1 =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg', -1)  # -1 is used for unchanged image
img2 =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg', -1)  # -1 is used for unchanged image

img1 =cv2.resize(img1,(400,400))
img2 =cv2.resize(img2,(400,400))

# AddWeighted two images 
img_add = cv2.addWeighted(img1,1, img2, 0.5,1)  # add two images change parameters
cv2.imshow('lion and Cat Image Add',img_add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [172]:
img1 =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg', -1)  # -1 is used for unchanged image
img2 =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg', -1)  # -1 is used for unchanged image

img1 =cv2.resize(img1,(400,400))
img2 =cv2.resize(img2,(400,400))

# AddWeighted two images 
img_add = cv2.subtract(img1, img2)  # subtract two images
cv2.imshow('lion and Cat Image Add',img_add)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 8. Edge Detection using OpenCV(Canny)

In [180]:
img =cv2.imread(r'E:\Computer-Vision\Images\Uzair.jpg', -1)  # -1 is used for unchanged image
img =cv2.resize(img,(300,300))
print(img.shape)  # shape of image

new_img =cv2.Canny(img,100,200,apertureSize =5,L2gradient=True)  # Edge detection using Canny method change threshold values for clear edges
print(new_img.shape)  # shape of new image after edge detection

cv2.imshow('Orginal Image',img)
cv2.imshow('Edge Detection Image',new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(300, 300, 3)
(300, 300)


# 9.Image Scaling, Rotating using OpenCV  

In [15]:
org_img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
res_img =cv2.resize(img,(300,400))

cv2.imshow('Orginal Image',org_img)
cv2.imshow('Scaling Image',res_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
org_img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
res_img =cv2.resize(img,(300,400))
org_img = cv2.resize(org_img, (300, 400))  # Resize original image to match resized image dimensions

# Rotate the resized image by 45 degrees
w,h =res_img.shape[0],res_img.shape[1]  # Get width and height of resized image
m = cv2.getRotationMatrix2D(center=(w/2,h/2), angle=45,scale =1)  # Get rotation matrix for image rotation
new_img = cv2.warpAffine(res_img, m, (h, w))  # Apply rotation to the resized image

# Stack original and rotated images horizontally
h =np.hstack((org_img,new_img))  
cv2.imshow('Orginal Image and Rotate Image',h)

cv2.waitKey(0)
cv2.destroyAllWindows()

# 10. Image bluring using OpenCV

In [ ]:
org_img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
res_img =cv2.resize(img,(300,400))
org_img = cv2.resize(org_img, (300, 400))  # Resize original image to match resized image dimensions

# Blurring the resized image using GaussianBlur
# Three Type of blurring methods (Gaussian, Median, Bilateral)

blurred_img = cv2.GaussianBlur(res_img, (15, 15), 0)  # Apply Gaussian blur with a kernel size of 15x15
# m_blurred_img = cv2.medianBlur(blurred_img, 15)  # Apply median blur with a kernel size of 15
# b_blurred_img =cv2.bilateralFilter(blurred_img, d=15, sigmaColor=75, sigmaSpace=75)  # Apply bilateral filter with specified parameters


# Stack original and rotated images horizontally
g =np.hstack((org_img,blurred_img))  
cv2.imshow('Orginal Image and Rotate Image',g)

cv2.waitKey(0)
cv2.destroyAllWindows()

# 11.imwrite method using OpenCV

In [ ]:
org_img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
res_img =cv2.resize(org_img,(300,400))


h =np.hstack((res_img,res_img)) 
v =np.vstack((h,h))  

 # imwrite function Save the image to a file
imwrite_img =cv2.imwrite('imwrite image.jpg', v) 

cv2.imshow('ImWrite Funtion',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 12.MakeBorder using OpenCV

In [ ]:
img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
img =cv2.resize(org_img,(300,400))

# Draw Border side of Images
border_img =cv2.copyMakeBorder(img,20,20,20,20, borderType=cv2.BORDER_CONSTANT, value=2)


cv2.imshow('Border Funtion',border_img)
cv2.waitKey(0)
cv2.destroyAllWindows()