# 1. Read and Show Image

In [2]:
import cv2
import numpy as np

## Image Read and Show

In [4]:
img =cv2.imread(r'E:\Computer-Vision\Images\boat.jpg') # read image
cv2.imshow('Boat Image',img) # show image
cv2.waitKey(10000)  # image frame wait time-ms and 0 pass keyboard any key press
# cv2.destroyAllWindows()  # all window close
cv2.destroyWindow('Boat Image')  # only one window close give particular window name


## Image Multiple Window Open

In [5]:
img =cv2.imread(r'E:\Computer-Vision\Images\boat.jpg') # read image
cv2.imshow('Boat Image',img) # show image
cv2.imshow('Boat Image',img) # show image
cv2.waitKey(0)  # image frame wait time-ms and 0 pass keyboard any key press
cv2.destroyAllWindows()  # all window close
# cv2.destroyWindow()  # only one window close

## Resize Image

In [6]:
img =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg') # read image

#Resize image width ,height
img =cv2.resize(img,(500,500))

cv2.imshow('Cat Image',img) # show image
cv2.waitKey(0)  # image frame wait time-ms and 0 pass keyboard any key press
# cv2.destroyAllWindows()  # all window close
cv2.destroyWindow('Cat Image')  # only one window close give particular window name


In [9]:
import numpy as np
v =np.array([[1,2,3,1,2,3],[1,2,3,1,2,3]])
v

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [10]:
img =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg') # read image
print(img) #RGB

[[[  5  22  35]
  [  7  24  37]
  [ 10  27  40]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 [[  8  25  38]
  [  9  26  39]
  [  9  28  41]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 [[ 13  30  43]
  [ 12  31  44]
  [ 12  31  46]
  ...
  [184 181 166]
  [184 181 166]
  [184 181 166]]

 ...

 [[  9  14  17]
  [  4   9  12]
  [  9  14  17]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]

 [[ 22  27  30]
  [  5  10  13]
  [  9  14  17]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]

 [[ 40  45  48]
  [ 10  15  18]
  [ 10  15  18]
  ...
  [156 158 158]
  [156 158 158]
  [156 158 158]]]


# 2. Show Multiple Image and Slide Show
### Horizontal and Vertical

In [11]:
img =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg')

#Resize image width ,height
img =cv2.resize(img,(200,200))

#Show horizontal multiple image in one frame
h =np.hstack((img,img))

#Show vertical multiple image in one frame
v =np.vstack((h,h))

cv2.imshow('Lion Image',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Slide Image Show

In [13]:
import os
# show all images with help of os
list_name =os.listdir(r'E:\Computer-Vision\Images')
list_name

['boat.jpg',
 'cat.jpg',
 'chair.jpg',
 'clock.jpg',
 'dog.jpg',
 'elephant.jpg',
 'fan.jpg',
 'Honda Civic.jpg',
 'laptop.jpg',
 'lion.jpg']

In [15]:
for name in list_name:
    path ='E:\\Computer-Vision\\Images'
    img_name = path + '\\' + name 
    img = cv2.imread(img_name)
    img =cv2.resize(img,(200,200))
    cv2.imshow('Different Images',img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()
    

# 3. Image imread Function (RGB,grayscale)

In [2]:
# 1 is used for RGB color image flag is 1
import cv2
img = cv2.imread(r'E:\Computer-Vision\Images\clock.jpg', 1)
img = cv2.resize(img,(200,200))
cv2.imshow("RGB Image flag = 1",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# 0 is used for grayscale image flag is 0
import cv2
img = cv2.imread(r'E:\Computer-Vision\Images\clock.jpg', 0)
img = cv2.resize(img,(200,200))
cv2.imshow("Grayscale Image flag = 0",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 4. Text Over a Image

In [1]:
import cv2


In [71]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\clock.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(500,600))

# Draw text on image parameters
img =img_get
text ='Clock Image' # text to be added
org = (150, 50)  # position of text
fontFace = cv2.FONT_HERSHEY_DUPLEX # font type
fontscale = 1 # font scale
color = (0, 255, 0)  # BGR color format
thickness = 2  # thickness of text
lineType =cv2.LINE_8 # line type
bottomLeftOrigin = False  # text origin



txt =cv2.putText(img, text, org, fontFace, fontscale, color, thickness, lineType, bottomLeftOrigin)

cv2.imshow('Clock Image',img_get) 
cv2.waitKey(0)
cv2.destroyAllWindows()


# 5. Draw Line and Rectangle on Image 

In [61]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(400,400))

# Draw line on image change parameters
img =cv2.line(img_get, pt1=(200, 100),pt2= (300 , 100), color =(255, 0, 0), thickness=4,lineType =4)  # line start point, end point, color, thickness

cv2.imshow('Lion Image',img) 
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(400,400))

# Draw text on image parameters
img =img_get
text ='lion' # text to be added
org = (170, 25)  # position of text
fontFace = 2 # font type
fontscale = 1 # font scale
color = (0, 0, 255)  # BGR color format
thickness = 2  # thickness of text
lineType = 16 # line type
bottomLeftOrigin = False  # text origin

txt =cv2.putText(img, text, org, fontFace, fontscale, color, thickness, lineType, bottomLeftOrigin)

 
# Draw Rectangle on image change parameters
img =cv2.rectangle(img_get, pt1=(170, 30),pt2= (320 , 300), color =(0, 255, 0), thickness=2,lineType =16)  # line start point, end point, color, thickness

cv2.imshow('Lion Image',img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# 6. Draw Circle and Elllipse On Image

In [122]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\dog.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(400,400))

# Draw circle on image change parameters if thickness =-1 then circle is filled
img =cv2.circle(img =img_get, center=(300, 100), radius=65, color=(0, 0, 255), thickness=2, lineType=16)  # center point, radius, color, thickness



cv2.imshow('Dog Image',img_get) 
cv2.waitKey(0)
cv2.destroyAllWindows()


In [159]:
img_get =cv2.imread(r'E:\Computer-Vision\Images\dog.jpg', -1)  # -1 is used for unchanged image
img_get =cv2.resize(img_get,(400,400))


# write text on image
txt_img =cv2.putText(img_get, 'Dog', (250, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2, cv2.LINE_AA)



# Draw Ellipsis on image change parameters if thickness =-1 then circle is filled
img =cv2.ellipse(img =img_get, center=(305, 115), axes =(35,60), 
                 angle =10, startAngle =0, endAngle =360,
                 color=(0, 0, 255), thickness=2,
                 lineType=16)  # center point , color, thickness


cv2.imshow('Dog Image',img_get) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# 7. Arithmetic Operation on Image using Opencv

In [173]:
img1 =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg', -1)  # -1 is used for unchanged image
img2 =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg', -1)  # -1 is used for unchanged image

img1 =cv2.resize(img1,(400,400))
img2 =cv2.resize(img2,(400,400))

# AddWeighted two images 
img_add = cv2.addWeighted(img1,1, img2, 0.5,1)  # add two images change parameters
cv2.imshow('lion and Cat Image Add',img_add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [172]:
img1 =cv2.imread(r'E:\Computer-Vision\Images\lion.jpg', -1)  # -1 is used for unchanged image
img2 =cv2.imread(r'E:\Computer-Vision\Images\cat.jpg', -1)  # -1 is used for unchanged image

img1 =cv2.resize(img1,(400,400))
img2 =cv2.resize(img2,(400,400))

# AddWeighted two images 
img_add = cv2.subtract(img1, img2)  # subtract two images
cv2.imshow('lion and Cat Image Add',img_add)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 8. Edge Detection using OpenCV(Canny)

In [180]:
img =cv2.imread(r'E:\Computer-Vision\Images\Uzair.jpg', -1)  # -1 is used for unchanged image
img =cv2.resize(img,(300,300))
print(img.shape)  # shape of image

new_img =cv2.Canny(img,100,200,apertureSize =5,L2gradient=True)  # Edge detection using Canny method change threshold values for clear edges
print(new_img.shape)  # shape of new image after edge detection

cv2.imshow('Orginal Image',img)
cv2.imshow('Edge Detection Image',new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(300, 300, 3)
(300, 300)


# 9.Image Scaling, Rotating using OpenCV  

In [15]:
org_img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
res_img =cv2.resize(img,(300,400))

cv2.imshow('Orginal Image',org_img)
cv2.imshow('Scaling Image',res_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
org_img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
res_img =cv2.resize(img,(300,400))
org_img = cv2.resize(org_img, (300, 400))  # Resize original image to match resized image dimensions

# Rotate the resized image by 45 degrees
w,h =res_img.shape[0],res_img.shape[1]  # Get width and height of resized image
m = cv2.getRotationMatrix2D(center=(w/2,h/2), angle=45,scale =1)  # Get rotation matrix for image rotation
new_img = cv2.warpAffine(res_img, m, (h, w))  # Apply rotation to the resized image

# Stack original and rotated images horizontally
h =np.hstack((org_img,new_img))  
cv2.imshow('Orginal Image and Rotate Image',h)

cv2.waitKey(0)
cv2.destroyAllWindows()

# 10. Image bluring using OpenCV

In [ ]:
org_img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
res_img =cv2.resize(img,(300,400))
org_img = cv2.resize(org_img, (300, 400))  # Resize original image to match resized image dimensions

# Blurring the resized image using GaussianBlur
# Three Type of blurring methods (Gaussian, Median, Bilateral)

blurred_img = cv2.GaussianBlur(res_img, (15, 15), 0)  # Apply Gaussian blur with a kernel size of 15x15
# m_blurred_img = cv2.medianBlur(blurred_img, 15)  # Apply median blur with a kernel size of 15
# b_blurred_img =cv2.bilateralFilter(blurred_img, d=15, sigmaColor=75, sigmaSpace=75)  # Apply bilateral filter with specified parameters


# Stack original and rotated images horizontally
g =np.hstack((org_img,blurred_img))  
cv2.imshow('Orginal Image and Rotate Image',g)

cv2.waitKey(0)
cv2.destroyAllWindows()

# 11.imwrite method using OpenCV

In [19]:
org_img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
res_img =cv2.resize(org_img,(300,400))


h =np.hstack((res_img,res_img)) 
v =np.vstack((h,h))  

 # imwrite function Save the image to a file
imwrite_img =cv2.imwrite('imwrite image.jpg', v) 

cv2.imshow('ImWrite Funtion',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 12.MakeBorder using OpenCV

In [ ]:
img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
img =cv2.resize(org_img,(300,400))

# Draw Border side of Images
border_img =cv2.copyMakeBorder(img,20,20,20,20, borderType=cv2.BORDER_CONSTANT, value=2)


cv2.imshow('Border Funtion',border_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 13.Play a video using OpenCV

In [47]:
# Open video file
cap =cv2.VideoCapture(r'E:\Computer-Vision\Images\Video.mp4')

# Check if the video is opened successfully  
while cap.isOpened():
    r,frame =cap.read()
    if r == True:
        frame =cv2.resize(frame,(500,500))  # Resize video frame
        cv2.imshow('Video Frame',frame)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break

cap.release()  # Release the video capture object

cv2.destroyAllWindows() # Close all OpenCV windows


# 14.Capture Video from the Camera using OpenCV

In [31]:
cap =cv2.VideoCapture(0) # Capture video from the camera

while True:
    r,frame =cap.read()
    if r == True:
        frame =cv2.resize(frame,(500,500))  # Resize video frame
        cv2.imshow('Camera Video Frame',frame)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break

cap.release()  # Release the video capture object

cv2.destroyAllWindows() # Close all OpenCV windows

# 15.Slow and Fast Motion Video

In [35]:
cap =cv2.VideoCapture(r'E:\Computer-Vision\Images\Video.mp4') # Capture video from the camera

while cap.isOpened():
    r,frame =cap.read()
    if r == True:
        frame =cv2.resize(frame,(500,500))  # Resize video frame
        cv2.imshow('Camera Video Frame',frame)
        
        # Slow and Fast Motion Video if you want to slow down the video, increase the wait time
        # if you want to speed up the video, decrease the wait time
        if cv2.waitKey(5) & 0xff == ord('q'): # #fast
        # if cv2.waitKey(50) & 0xff == ord('q'): #slow
            break
    else:
        break

cap.release()  # Release the video capture object

cv2.destroyAllWindows() # Close all OpenCV windows 

# 16. Cropping Image or Image Translation using OpenCV 

In [43]:
img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
img =cv2.resize(org_img,(300,400))

# Cropping Image or Image Translation using OpenCV
m = np.float32([[1, 0, 50], [0, 1, 100]])  # Translation matrix to translate the image by 50 pixels in x and y direction
new_img =cv2.warpAffine(img,m,(300,400) )  # Translate the image by 50 pixels in x and y direction

cv2.imshow('Orginal Image',img)
cv2.imshow('Map Image',m)
cv2.imshow('Crop Image',new_img)

cv2.waitKey(0)
cv2.destroyAllWindows() # Close all OpenCV windows 

# 17.Background subtraction using OpenCV
### Agr ham kasi video ma sa chata ha k sirf wohi object detect ho jiski hama zorart ha to usko use karta ha

In [49]:
# Open video file
cap =cv2.VideoCapture(r'E:\Computer-Vision\Images\Video.mp4')

# Create background subtractor object
sub_m = cv2.createBackgroundSubtractorMOG2() 

# Check if the video is opened successfully  
while cap.isOpened():
    r,frame = cap.read()
    if r == True:
        frame =cv2.resize(frame,(500,400))  # Resize video frame  
        sub_video = sub_m.apply(frame)  
        cv2.imshow('Background Subtraction Video Frame',sub_video)
        cv2.imshow('Video Frame',frame)
        if cv2.waitKey(20) & 0xff == ord('q'):
            break
    else:
        break

cap.release()  # Release the video capture object

cv2.destroyAllWindows() # Close all OpenCV windows


# 18.Extract images from video using OpenCV

In [51]:
# Open video file
cap =cv2.VideoCapture(r'E:\Computer-Vision\Images\Video.mp4')

c =0
# Check if the video is opened successfully  
while True:
    r,frame =cap.read()
    if r == True:
        frame =cv2.resize(frame,(500,500))  # Resize video frame
        
        # Extract images from video using OpenCV
        
        filename = 'E://Computer-Vision//Images//org_img'+str(c)+'.jpg'  # Create a filename for the extracted image
        cv2.imwrite(filename, frame)  # Save the extracted image to the file
        cv2.imshow('Extracted Image', frame)
        c =c+1  # Increment the counter for the next image filename
        cv2.imshow('Video Frame',frame)
        
        
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break

cap.release()  # Release the video capture object

cv2.destroyAllWindows() # Close all OpenCV windows


# 19. cvtColor method OpenCV (Chnage Color of Image)

In [ ]:
img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
img =cv2.resize(img,(300,400))

# Change Color of Image using cvtColor method OpenCV
new_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # Convert the image to grayscale


cv2.imshow('Orginal Image',img)
cv2.imshow('Change Color Image',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 20. Crop Image using OpenCV Python

In [18]:
img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
img =cv2.resize(img,(300,400))

# Crop Image using OpenCV Python
crop =img[50:300,:] 

cv2.imshow('Orginal Image',img)
cv2.imshow('Crop Image',crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 21. Flip , Rotate & Transpose using OpenCV

In [18]:
img =cv2.imread(r'E:\Computer-Vision\Images\Person.jpg', -1)  # -1 is used for unchanged image
img =cv2.resize(img,(300,400))

# Flip image using OpenCV
img_flip =cv2.flip(img,1) # y-axis flip
# img_flip =cv2.flip(img,0) # x-axis flip

# Rotate Images
Rotate_img =cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)

# Transpose Image
transpose_img = cv2.transpose(img)  # Transpose the image

cv2.imshow('Orginal Image',img)
cv2.imshow('Flip Image',img_flip)
cv2.imshow('Rotate Image',Rotate_img)
cv2.imshow('Transpose Image',transpose_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 22.Camera Video Record & Saving color & Grayscale a Video using OpenCV

In [24]:
cap =cv2.VideoCapture(0)


# 1.Record Video from Camera using OpenCV
video_record =cv2.VideoWriter_fourcc(*'XVID')  # Define the codec and create VideoWriter object
out = cv2.VideoWriter('output_video.mp4', video_record, 20.0, (640, 480))  # Create VideoWriter object to save the video


while cap.isOpened():
    r,frame =cap.read()
    if r == True:
        # 2. flip us lai kia taqa hamri video frame mirror image ban jaye
        frame =cv2.flip(frame,1)
        # 3. video save
        out.write(frame)
        
        frame =cv2.resize(frame,(500,500)) 
        cv2.imshow('Camera Video Frame',frame)
        if cv2.waitKey(1) & 0xff == ord('q'):
            break
    else:
        break

cap.release() 
# 4. Release the video capture object
out.release()

cv2.destroyAllWindows() 

## Convert Video Into GrayScale

In [26]:
cap =cv2.VideoCapture(0)


# 1.Record Video from Camera using OpenCV
video_record =cv2.VideoWriter_fourcc(*'XVID')  # Define the codec and create VideoWriter object
# Add 0 as a parameter for save grayscale video 
out = cv2.VideoWriter('gray_output_video.mp4', video_record, 20.0, (640, 480),0)  # Create VideoWriter object to save the video


while cap.isOpened():
    r,frame =cap.read()
    if r == True:
        # 1. Convert video frame to grayscale
        frame =cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        
        # 2. flip us lai kia taqa hamri video frame mirror image ban jaye
        frame =cv2.flip(frame,1)
        # 3. video save
        out.write(frame)
        
        frame =cv2.resize(frame,(500,500)) 
        cv2.imshow('Camera Video Frame',frame)
        if cv2.waitKey(1) & 0xff == ord('q'):
            break
    else:
        break

cap.release() 
# 4. Release the video capture object
out.release()

cv2.destroyAllWindows() 